
module.exports = {
    attributes: {
        email: { type: 'string' },
        category: { type: 'string'},
        brand: { type: 'string'},
        product_name: { type: 'string'},
        product_description: { type: 'string'},
        parcel_weight: { type: 'string'},
        parcel_length: { type: 'string'},
        parcel_width: { type: 'string'},
        parcel_height: { type: 'string'},
        delivery: { type: 'string'},
        gtin_type: { type: 'string'},
        gtin_code: { type: 'string'},
        property_value_1: { type: 'string'},
        property_value_2: { type: 'string'},
        property_1_image: { type: 'string'},
        price: { type: 'string'},
        quantity: { type: 'string'},
        seller_sku: { type: 'string'},
        main_image: { type: 'string'},
        image_2: { type: 'string'},
        image_3: { type: 'string'},
        image_4: { type: 'string'},
        image_5: { type: 'string'},
        image_6: { type: 'string'},
        image_7: { type: 'string'},
        image_8: { type: 'string'},
        image_9: { type: 'string'},
        size_chart: { type: 'string'},
        product_property_100157: { type: 'string'},
        product_property_100198: { type: 'string'},
        product_property_100393: { type: 'string'},
        product_property_100394: { type: 'string'},
        product_property_100395: { type: 'string'},
        product_property_100396: { type: 'string'},
        product_property_100397: { type: 'string'},
        product_property_100398: { type: 'string'},
        product_property_100399: { type: 'string'},
        product_property_100400: { type: 'string'},
        product_property_100403: { type: 'string'},
        aimed_product_status: { type: 'string'},

    },

};
